# Generated by Django 2.2.6 on 2019-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('username', models.CharField(max_length=200, primary_key='true', serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=200, primary_key='true', serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(max_length=200, primary_key='true', serialize=False),
        ),
    ]
