# Generated by Django 2.2.6 on 2019-11-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20191105_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
