# Generated by Django 2.2.6 on 2019-11-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_delete_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=1000)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=200)),
                ('product_pic', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('locality', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('check_email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=1000)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=200)),
                ('product_pic', models.CharField(max_length=1000)),
            ],
        ),
    ]
